/*
 * Extractor Engine API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.76(UAT)
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CandidateQualificationCompactDto model module.
 * @module model/CandidateQualificationCompactDto
 * @version v3.76(UAT)
 */
export class CandidateQualificationCompactDto {
  /**
   * Constructs a new <code>CandidateQualificationCompactDto</code>.
   * @alias module:model/CandidateQualificationCompactDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CandidateQualificationCompactDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CandidateQualificationCompactDto} obj Optional instance to populate.
   * @return {module:model/CandidateQualificationCompactDto} The populated <code>CandidateQualificationCompactDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CandidateQualificationCompactDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('educationInstituteId'))
        obj.educationInstituteId = ApiClient.convertToType(data['educationInstituteId'], 'Number');
      if (data.hasOwnProperty('institutionName'))
        obj.institutionName = ApiClient.convertToType(data['institutionName'], 'String');
      if (data.hasOwnProperty('startDate'))
        obj.startDate = ApiClient.convertToType(data['startDate'], 'Date');
      if (data.hasOwnProperty('endDate'))
        obj.endDate = ApiClient.convertToType(data['endDate'], 'Date');
      if (data.hasOwnProperty('degreeId'))
        obj.degreeId = ApiClient.convertToType(data['degreeId'], 'Number');
      if (data.hasOwnProperty('fieldOfStudyId'))
        obj.fieldOfStudyId = ApiClient.convertToType(data['fieldOfStudyId'], 'Number');
      if (data.hasOwnProperty('candidateId'))
        obj.candidateId = ApiClient.convertToType(data['candidateId'], 'Number');
      if (data.hasOwnProperty('experienceInMonths'))
        obj.experienceInMonths = ApiClient.convertToType(data['experienceInMonths'], 'Number');
      if (data.hasOwnProperty('isStillPerceiving'))
        obj.isStillPerceiving = ApiClient.convertToType(data['isStillPerceiving'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
CandidateQualificationCompactDto.prototype.id = undefined;

/**
 * @member {Number} educationInstituteId
 */
CandidateQualificationCompactDto.prototype.educationInstituteId = undefined;

/**
 * @member {String} institutionName
 */
CandidateQualificationCompactDto.prototype.institutionName = undefined;

/**
 * @member {Date} startDate
 */
CandidateQualificationCompactDto.prototype.startDate = undefined;

/**
 * @member {Date} endDate
 */
CandidateQualificationCompactDto.prototype.endDate = undefined;

/**
 * @member {Number} degreeId
 */
CandidateQualificationCompactDto.prototype.degreeId = undefined;

/**
 * @member {Number} fieldOfStudyId
 */
CandidateQualificationCompactDto.prototype.fieldOfStudyId = undefined;

/**
 * @member {Number} candidateId
 */
CandidateQualificationCompactDto.prototype.candidateId = undefined;

/**
 * @member {Number} experienceInMonths
 */
CandidateQualificationCompactDto.prototype.experienceInMonths = undefined;

/**
 * @member {Boolean} isStillPerceiving
 */
CandidateQualificationCompactDto.prototype.isStillPerceiving = undefined;

