/*
 * Extractor Engine API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.76(UAT)
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CandidateCertificateCreateDto model module.
 * @module model/CandidateCertificateCreateDto
 * @version v3.76(UAT)
 */
export class CandidateCertificateCreateDto {
  /**
   * Constructs a new <code>CandidateCertificateCreateDto</code>.
   * @alias module:model/CandidateCertificateCreateDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CandidateCertificateCreateDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CandidateCertificateCreateDto} obj Optional instance to populate.
   * @return {module:model/CandidateCertificateCreateDto} The populated <code>CandidateCertificateCreateDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CandidateCertificateCreateDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('startDate'))
        obj.startDate = ApiClient.convertToType(data['startDate'], 'Date');
      if (data.hasOwnProperty('endDate'))
        obj.endDate = ApiClient.convertToType(data['endDate'], 'Date');
      if (data.hasOwnProperty('authority'))
        obj.authority = ApiClient.convertToType(data['authority'], 'String');
      if (data.hasOwnProperty('certificationUrl'))
        obj.certificationUrl = ApiClient.convertToType(data['certificationUrl'], 'String');
      if (data.hasOwnProperty('certificateId'))
        obj.certificateId = ApiClient.convertToType(data['certificateId'], 'Number');
      if (data.hasOwnProperty('candidateId'))
        obj.candidateId = ApiClient.convertToType(data['candidateId'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
CandidateCertificateCreateDto.prototype.id = undefined;

/**
 * @member {String} title
 */
CandidateCertificateCreateDto.prototype.title = undefined;

/**
 * @member {Date} startDate
 */
CandidateCertificateCreateDto.prototype.startDate = undefined;

/**
 * @member {Date} endDate
 */
CandidateCertificateCreateDto.prototype.endDate = undefined;

/**
 * @member {String} authority
 */
CandidateCertificateCreateDto.prototype.authority = undefined;

/**
 * @member {String} certificationUrl
 */
CandidateCertificateCreateDto.prototype.certificationUrl = undefined;

/**
 * @member {Number} certificateId
 */
CandidateCertificateCreateDto.prototype.certificateId = undefined;

/**
 * @member {Number} candidateId
 */
CandidateCertificateCreateDto.prototype.candidateId = undefined;

