/*
 * Extractor Engine API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.76(UAT)
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {DocumentDto} from './DocumentDto';

/**
 * The CandidateCollegeImageDto model module.
 * @module model/CandidateCollegeImageDto
 * @version v3.76(UAT)
 */
export class CandidateCollegeImageDto {
  /**
   * Constructs a new <code>CandidateCollegeImageDto</code>.
   * @alias module:model/CandidateCollegeImageDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CandidateCollegeImageDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CandidateCollegeImageDto} obj Optional instance to populate.
   * @return {module:model/CandidateCollegeImageDto} The populated <code>CandidateCollegeImageDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CandidateCollegeImageDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('collegeImageId'))
        obj.collegeImageId = ApiClient.convertToType(data['collegeImageId'], 'Number');
      if (data.hasOwnProperty('collegeImage'))
        obj.collegeImage = DocumentDto.constructFromObject(data['collegeImage']);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
CandidateCollegeImageDto.prototype.id = undefined;

/**
 * @member {Number} collegeImageId
 */
CandidateCollegeImageDto.prototype.collegeImageId = undefined;

/**
 * @member {module:model/DocumentDto} collegeImage
 */
CandidateCollegeImageDto.prototype.collegeImage = undefined;

