/*
 * Extractor Engine API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.76(UAT)
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ParsedData} from './ParsedData';

/**
 * The ChatGPTMapDto model module.
 * @module model/ChatGPTMapDto
 * @version v3.76(UAT)
 */
export class ChatGPTMapDto {
  /**
   * Constructs a new <code>ChatGPTMapDto</code>.
   * @alias module:model/ChatGPTMapDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ChatGPTMapDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChatGPTMapDto} obj Optional instance to populate.
   * @return {module:model/ChatGPTMapDto} The populated <code>ChatGPTMapDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ChatGPTMapDto();
      if (data.hasOwnProperty('parsedData'))
        obj.parsedData = ParsedData.constructFromObject(data['parsedData']);
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {module:model/ParsedData} parsedData
 */
ChatGPTMapDto.prototype.parsedData = undefined;

/**
 * @member {Number} status
 */
ChatGPTMapDto.prototype.status = undefined;

