/*
 * Extractor Engine API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.76(UAT)
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CityEditDto model module.
 * @module model/CityEditDto
 * @version v3.76(UAT)
 */
export class CityEditDto {
  /**
   * Constructs a new <code>CityEditDto</code>.
   * @alias module:model/CityEditDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CityEditDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CityEditDto} obj Optional instance to populate.
   * @return {module:model/CityEditDto} The populated <code>CityEditDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CityEditDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'String');
      if (data.hasOwnProperty('pinCode'))
        obj.pinCode = ApiClient.convertToType(data['pinCode'], 'Number');
      if (data.hasOwnProperty('stdCode'))
        obj.stdCode = ApiClient.convertToType(data['stdCode'], 'Number');
      if (data.hasOwnProperty('stateId'))
        obj.stateId = ApiClient.convertToType(data['stateId'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
CityEditDto.prototype.id = undefined;

/**
 * @member {String} name
 */
CityEditDto.prototype.name = undefined;

/**
 * @member {String} code
 */
CityEditDto.prototype.code = undefined;

/**
 * @member {Number} pinCode
 */
CityEditDto.prototype.pinCode = undefined;

/**
 * @member {Number} stdCode
 */
CityEditDto.prototype.stdCode = undefined;

/**
 * @member {Number} stateId
 */
CityEditDto.prototype.stateId = undefined;

