/*
 * Extractor Engine API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.76(UAT)
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {BusinessVerticalDto} from './BusinessVerticalDto';
import {ClientAndAddressDto} from './ClientAndAddressDto';
import {ClientContractDto} from './ClientContractDto';
import {ClientStatus} from './ClientStatus';
import {ContactDto} from './ContactDto';

/**
 * The ClientDto model module.
 * @module model/ClientDto
 * @version v3.76(UAT)
 */
export class ClientDto {
  /**
   * Constructs a new <code>ClientDto</code>.
   * @alias module:model/ClientDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ClientDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ClientDto} obj Optional instance to populate.
   * @return {module:model/ClientDto} The populated <code>ClientDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ClientDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('uniqueGuid'))
        obj.uniqueGuid = ApiClient.convertToType(data['uniqueGuid'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('gstNumber'))
        obj.gstNumber = ApiClient.convertToType(data['gstNumber'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ClientStatus.constructFromObject(data['status']);
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'String');
      if (data.hasOwnProperty('isBranched'))
        obj.isBranched = ApiClient.convertToType(data['isBranched'], 'Boolean');
      if (data.hasOwnProperty('webSite'))
        obj.webSite = ApiClient.convertToType(data['webSite'], 'String');
      if (data.hasOwnProperty('companySize'))
        obj.companySize = ApiClient.convertToType(data['companySize'], 'String');
      if (data.hasOwnProperty('dateOfOnBoarding'))
        obj.dateOfOnBoarding = ApiClient.convertToType(data['dateOfOnBoarding'], 'Date');
      if (data.hasOwnProperty('typeOfService'))
        obj.typeOfService = ApiClient.convertToType(data['typeOfService'], 'String');
      if (data.hasOwnProperty('assignment'))
        obj.assignment = ApiClient.convertToType(data['assignment'], 'String');
      if (data.hasOwnProperty('brief'))
        obj.brief = ApiClient.convertToType(data['brief'], 'String');
      if (data.hasOwnProperty('isActive'))
        obj.isActive = ApiClient.convertToType(data['isActive'], 'Boolean');
      if (data.hasOwnProperty('companyProfile'))
        obj.companyProfile = ApiClient.convertToType(data['companyProfile'], 'String');
      if (data.hasOwnProperty('contacts'))
        obj.contacts = ApiClient.convertToType(data['contacts'], [ContactDto]);
      if (data.hasOwnProperty('clientContracts'))
        obj.clientContracts = ApiClient.convertToType(data['clientContracts'], [ClientContractDto]);
      if (data.hasOwnProperty('businessVerticalId'))
        obj.businessVerticalId = ApiClient.convertToType(data['businessVerticalId'], 'Number');
      if (data.hasOwnProperty('businessVertical'))
        obj.businessVertical = BusinessVerticalDto.constructFromObject(data['businessVertical']);
      if (data.hasOwnProperty('clientAddresses'))
        obj.clientAddresses = ApiClient.convertToType(data['clientAddresses'], [ClientAndAddressDto]);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
ClientDto.prototype.id = undefined;

/**
 * @member {String} uniqueGuid
 */
ClientDto.prototype.uniqueGuid = undefined;

/**
 * @member {String} name
 */
ClientDto.prototype.name = undefined;

/**
 * @member {String} displayName
 */
ClientDto.prototype.displayName = undefined;

/**
 * @member {String} gstNumber
 */
ClientDto.prototype.gstNumber = undefined;

/**
 * @member {module:model/ClientStatus} status
 */
ClientDto.prototype.status = undefined;

/**
 * @member {String} code
 */
ClientDto.prototype.code = undefined;

/**
 * @member {Boolean} isBranched
 */
ClientDto.prototype.isBranched = undefined;

/**
 * @member {String} webSite
 */
ClientDto.prototype.webSite = undefined;

/**
 * @member {String} companySize
 */
ClientDto.prototype.companySize = undefined;

/**
 * @member {Date} dateOfOnBoarding
 */
ClientDto.prototype.dateOfOnBoarding = undefined;

/**
 * @member {String} typeOfService
 */
ClientDto.prototype.typeOfService = undefined;

/**
 * @member {String} assignment
 */
ClientDto.prototype.assignment = undefined;

/**
 * @member {String} brief
 */
ClientDto.prototype.brief = undefined;

/**
 * @member {Boolean} isActive
 */
ClientDto.prototype.isActive = undefined;

/**
 * @member {String} companyProfile
 */
ClientDto.prototype.companyProfile = undefined;

/**
 * @member {Array.<module:model/ContactDto>} contacts
 */
ClientDto.prototype.contacts = undefined;

/**
 * @member {Array.<module:model/ClientContractDto>} clientContracts
 */
ClientDto.prototype.clientContracts = undefined;

/**
 * @member {Number} businessVerticalId
 */
ClientDto.prototype.businessVerticalId = undefined;

/**
 * @member {module:model/BusinessVerticalDto} businessVertical
 */
ClientDto.prototype.businessVertical = undefined;

/**
 * @member {Array.<module:model/ClientAndAddressDto>} clientAddresses
 */
ClientDto.prototype.clientAddresses = undefined;

