/*
 * Extractor Engine API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.76(UAT)
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ClientInterviewRoundCompactDto model module.
 * @module model/ClientInterviewRoundCompactDto
 * @version v3.76(UAT)
 */
export class ClientInterviewRoundCompactDto {
  /**
   * Constructs a new <code>ClientInterviewRoundCompactDto</code>.
   * @alias module:model/ClientInterviewRoundCompactDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ClientInterviewRoundCompactDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ClientInterviewRoundCompactDto} obj Optional instance to populate.
   * @return {module:model/ClientInterviewRoundCompactDto} The populated <code>ClientInterviewRoundCompactDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ClientInterviewRoundCompactDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('uniqueGuid'))
        obj.uniqueGuid = ApiClient.convertToType(data['uniqueGuid'], 'String');
      if (data.hasOwnProperty('roundName'))
        obj.roundName = ApiClient.convertToType(data['roundName'], 'String');
      if (data.hasOwnProperty('clientId'))
        obj.clientId = ApiClient.convertToType(data['clientId'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
ClientInterviewRoundCompactDto.prototype.id = undefined;

/**
 * @member {String} uniqueGuid
 */
ClientInterviewRoundCompactDto.prototype.uniqueGuid = undefined;

/**
 * @member {String} roundName
 */
ClientInterviewRoundCompactDto.prototype.roundName = undefined;

/**
 * @member {Number} clientId
 */
ClientInterviewRoundCompactDto.prototype.clientId = undefined;

