/*
 * Extractor Engine API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.76(UAT)
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CountryEditDto model module.
 * @module model/CountryEditDto
 * @version v3.76(UAT)
 */
export class CountryEditDto {
  /**
   * Constructs a new <code>CountryEditDto</code>.
   * @alias module:model/CountryEditDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CountryEditDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CountryEditDto} obj Optional instance to populate.
   * @return {module:model/CountryEditDto} The populated <code>CountryEditDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CountryEditDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'String');
      if (data.hasOwnProperty('twoLetterCode'))
        obj.twoLetterCode = ApiClient.convertToType(data['twoLetterCode'], 'String');
      if (data.hasOwnProperty('threeLetterCode'))
        obj.threeLetterCode = ApiClient.convertToType(data['threeLetterCode'], 'String');
      if (data.hasOwnProperty('numericCode'))
        obj.numericCode = ApiClient.convertToType(data['numericCode'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
CountryEditDto.prototype.id = undefined;

/**
 * @member {String} name
 */
CountryEditDto.prototype.name = undefined;

/**
 * @member {String} code
 */
CountryEditDto.prototype.code = undefined;

/**
 * @member {String} twoLetterCode
 */
CountryEditDto.prototype.twoLetterCode = undefined;

/**
 * @member {String} threeLetterCode
 */
CountryEditDto.prototype.threeLetterCode = undefined;

/**
 * @member {Number} numericCode
 */
CountryEditDto.prototype.numericCode = undefined;

