/*
 * Extractor Engine API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.76(UAT)
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ContentDto} from './ContentDto';
import {IntegrationDto} from './IntegrationDto';

/**
 * The CourseDto model module.
 * @module model/CourseDto
 * @version v3.76(UAT)
 */
export class CourseDto {
  /**
   * Constructs a new <code>CourseDto</code>.
   * @alias module:model/CourseDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CourseDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CourseDto} obj Optional instance to populate.
   * @return {module:model/CourseDto} The populated <code>CourseDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CourseDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('uniqueGuid'))
        obj.uniqueGuid = ApiClient.convertToType(data['uniqueGuid'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('duration'))
        obj.duration = ApiClient.convertToType(data['duration'], 'String');
      if (data.hasOwnProperty('link'))
        obj.link = ApiClient.convertToType(data['link'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('isActive'))
        obj.isActive = ApiClient.convertToType(data['isActive'], 'Boolean');
      if (data.hasOwnProperty('isApproved'))
        obj.isApproved = ApiClient.convertToType(data['isApproved'], 'Boolean');
      if (data.hasOwnProperty('integrationAmount'))
        obj.integrationAmount = ApiClient.convertToType(data['integrationAmount'], 'Number');
      if (data.hasOwnProperty('internalAmount'))
        obj.internalAmount = ApiClient.convertToType(data['internalAmount'], 'Number');
      if (data.hasOwnProperty('integrationId'))
        obj.integrationId = ApiClient.convertToType(data['integrationId'], 'Number');
      if (data.hasOwnProperty('integration'))
        obj.integration = IntegrationDto.constructFromObject(data['integration']);
      if (data.hasOwnProperty('content'))
        obj.content = ApiClient.convertToType(data['content'], [ContentDto]);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
CourseDto.prototype.id = undefined;

/**
 * @member {String} uniqueGuid
 */
CourseDto.prototype.uniqueGuid = undefined;

/**
 * @member {String} name
 */
CourseDto.prototype.name = undefined;

/**
 * @member {String} duration
 */
CourseDto.prototype.duration = undefined;

/**
 * @member {String} link
 */
CourseDto.prototype.link = undefined;

/**
 * @member {String} description
 */
CourseDto.prototype.description = undefined;

/**
 * @member {Boolean} isActive
 */
CourseDto.prototype.isActive = undefined;

/**
 * @member {Boolean} isApproved
 */
CourseDto.prototype.isApproved = undefined;

/**
 * @member {Number} integrationAmount
 */
CourseDto.prototype.integrationAmount = undefined;

/**
 * @member {Number} internalAmount
 */
CourseDto.prototype.internalAmount = undefined;

/**
 * @member {Number} integrationId
 */
CourseDto.prototype.integrationId = undefined;

/**
 * @member {module:model/IntegrationDto} integration
 */
CourseDto.prototype.integration = undefined;

/**
 * @member {Array.<module:model/ContentDto>} content
 */
CourseDto.prototype.content = undefined;

