/*
 * Extractor Engine API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.76(UAT)
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The DummyEditDto model module.
 * @module model/DummyEditDto
 * @version v3.76(UAT)
 */
export class DummyEditDto {
  /**
   * Constructs a new <code>DummyEditDto</code>.
   * @alias module:model/DummyEditDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DummyEditDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DummyEditDto} obj Optional instance to populate.
   * @return {module:model/DummyEditDto} The populated <code>DummyEditDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DummyEditDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('uniqueGuid'))
        obj.uniqueGuid = ApiClient.convertToType(data['uniqueGuid'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
DummyEditDto.prototype.id = undefined;

/**
 * @member {String} uniqueGuid
 */
DummyEditDto.prototype.uniqueGuid = undefined;

/**
 * @member {String} name
 */
DummyEditDto.prototype.name = undefined;

