/*
 * Extractor Engine API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.76(UAT)
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The FieldOfStudyCompactDto model module.
 * @module model/FieldOfStudyCompactDto
 * @version v3.76(UAT)
 */
export class FieldOfStudyCompactDto {
  /**
   * Constructs a new <code>FieldOfStudyCompactDto</code>.
   * @alias module:model/FieldOfStudyCompactDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>FieldOfStudyCompactDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FieldOfStudyCompactDto} obj Optional instance to populate.
   * @return {module:model/FieldOfStudyCompactDto} The populated <code>FieldOfStudyCompactDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new FieldOfStudyCompactDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('uniqueGuid'))
        obj.uniqueGuid = ApiClient.convertToType(data['uniqueGuid'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('isApproved'))
        obj.isApproved = ApiClient.convertToType(data['isApproved'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
FieldOfStudyCompactDto.prototype.id = undefined;

/**
 * @member {String} uniqueGuid
 */
FieldOfStudyCompactDto.prototype.uniqueGuid = undefined;

/**
 * @member {String} name
 */
FieldOfStudyCompactDto.prototype.name = undefined;

/**
 * @member {Boolean} isApproved
 */
FieldOfStudyCompactDto.prototype.isApproved = undefined;

