/*
 * Extractor Engine API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.76(UAT)
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GlobalConfigurationDto model module.
 * @module model/GlobalConfigurationDto
 * @version v3.76(UAT)
 */
export class GlobalConfigurationDto {
  /**
   * Constructs a new <code>GlobalConfigurationDto</code>.
   * @alias module:model/GlobalConfigurationDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GlobalConfigurationDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GlobalConfigurationDto} obj Optional instance to populate.
   * @return {module:model/GlobalConfigurationDto} The populated <code>GlobalConfigurationDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GlobalConfigurationDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('uniqueGuid'))
        obj.uniqueGuid = ApiClient.convertToType(data['uniqueGuid'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'Number');
      if (data.hasOwnProperty('count'))
        obj.count = ApiClient.convertToType(data['count'], 'Number');
      if (data.hasOwnProperty('isActive'))
        obj.isActive = ApiClient.convertToType(data['isActive'], 'Boolean');
      if (data.hasOwnProperty('remarks'))
        obj.remarks = ApiClient.convertToType(data['remarks'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
GlobalConfigurationDto.prototype.id = undefined;

/**
 * @member {String} uniqueGuid
 */
GlobalConfigurationDto.prototype.uniqueGuid = undefined;

/**
 * @member {Number} type
 */
GlobalConfigurationDto.prototype.type = undefined;

/**
 * @member {Number} count
 */
GlobalConfigurationDto.prototype.count = undefined;

/**
 * @member {Boolean} isActive
 */
GlobalConfigurationDto.prototype.isActive = undefined;

/**
 * @member {String} remarks
 */
GlobalConfigurationDto.prototype.remarks = undefined;

