/*
 * Extractor Engine API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.76(UAT)
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {InterviewStatus} from './InterviewStatus';
import {JDClientInterviewRoundPanelDto} from './JDClientInterviewRoundPanelDto';

/**
 * The JdClientInterviewRoundsDto model module.
 * @module model/JdClientInterviewRoundsDto
 * @version v3.76(UAT)
 */
export class JdClientInterviewRoundsDto {
  /**
   * Constructs a new <code>JdClientInterviewRoundsDto</code>.
   * @alias module:model/JdClientInterviewRoundsDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>JdClientInterviewRoundsDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/JdClientInterviewRoundsDto} obj Optional instance to populate.
   * @return {module:model/JdClientInterviewRoundsDto} The populated <code>JdClientInterviewRoundsDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new JdClientInterviewRoundsDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('uniqueGuid'))
        obj.uniqueGuid = ApiClient.convertToType(data['uniqueGuid'], 'String');
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'Date');
      if (data.hasOwnProperty('status'))
        obj.status = InterviewStatus.constructFromObject(data['status']);
      if (data.hasOwnProperty('roundName'))
        obj.roundName = ApiClient.convertToType(data['roundName'], 'String');
      if (data.hasOwnProperty('remarks'))
        obj.remarks = ApiClient.convertToType(data['remarks'], 'String');
      if (data.hasOwnProperty('mode'))
        obj.mode = ApiClient.convertToType(data['mode'], 'String');
      if (data.hasOwnProperty('link'))
        obj.link = ApiClient.convertToType(data['link'], 'String');
      if (data.hasOwnProperty('addressId'))
        obj.addressId = ApiClient.convertToType(data['addressId'], 'Number');
      if (data.hasOwnProperty('time'))
        obj.time = ApiClient.convertToType(data['time'], 'Date');
      if (data.hasOwnProperty('duration'))
        obj.duration = ApiClient.convertToType(data['duration'], 'String');
      if (data.hasOwnProperty('isRescheduled'))
        obj.isRescheduled = ApiClient.convertToType(data['isRescheduled'], 'Boolean');
      if (data.hasOwnProperty('jdClientInterviewId'))
        obj.jdClientInterviewId = ApiClient.convertToType(data['jdClientInterviewId'], 'Number');
      if (data.hasOwnProperty('jdClientInterviewRoundPanels'))
        obj.jdClientInterviewRoundPanels = ApiClient.convertToType(data['jdClientInterviewRoundPanels'], [JDClientInterviewRoundPanelDto]);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
JdClientInterviewRoundsDto.prototype.id = undefined;

/**
 * @member {String} uniqueGuid
 */
JdClientInterviewRoundsDto.prototype.uniqueGuid = undefined;

/**
 * @member {Date} _date
 */
JdClientInterviewRoundsDto.prototype._date = undefined;

/**
 * @member {module:model/InterviewStatus} status
 */
JdClientInterviewRoundsDto.prototype.status = undefined;

/**
 * @member {String} roundName
 */
JdClientInterviewRoundsDto.prototype.roundName = undefined;

/**
 * @member {String} remarks
 */
JdClientInterviewRoundsDto.prototype.remarks = undefined;

/**
 * @member {String} mode
 */
JdClientInterviewRoundsDto.prototype.mode = undefined;

/**
 * @member {String} link
 */
JdClientInterviewRoundsDto.prototype.link = undefined;

/**
 * @member {Number} addressId
 */
JdClientInterviewRoundsDto.prototype.addressId = undefined;

/**
 * @member {Date} time
 */
JdClientInterviewRoundsDto.prototype.time = undefined;

/**
 * @member {String} duration
 */
JdClientInterviewRoundsDto.prototype.duration = undefined;

/**
 * @member {Boolean} isRescheduled
 */
JdClientInterviewRoundsDto.prototype.isRescheduled = undefined;

/**
 * @member {Number} jdClientInterviewId
 */
JdClientInterviewRoundsDto.prototype.jdClientInterviewId = undefined;

/**
 * @member {Array.<module:model/JDClientInterviewRoundPanelDto>} jdClientInterviewRoundPanels
 */
JdClientInterviewRoundsDto.prototype.jdClientInterviewRoundPanels = undefined;

