/*
 * Extractor Engine API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.76(UAT)
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {InterviewStatus} from './InterviewStatus';
import {JdClientInterviewRoundsCreateDto} from './JdClientInterviewRoundsCreateDto';
import {ProgressiveStatus} from './ProgressiveStatus';

/**
 * The JdClientInterviewCreateDto model module.
 * @module model/JdClientInterviewCreateDto
 * @version v3.76(UAT)
 */
export class JdClientInterviewCreateDto {
  /**
   * Constructs a new <code>JdClientInterviewCreateDto</code>.
   * @alias module:model/JdClientInterviewCreateDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>JdClientInterviewCreateDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/JdClientInterviewCreateDto} obj Optional instance to populate.
   * @return {module:model/JdClientInterviewCreateDto} The populated <code>JdClientInterviewCreateDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new JdClientInterviewCreateDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('uniqueGuid'))
        obj.uniqueGuid = ApiClient.convertToType(data['uniqueGuid'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = InterviewStatus.constructFromObject(data['status']);
      if (data.hasOwnProperty('progressiveStatus'))
        obj.progressiveStatus = ProgressiveStatus.constructFromObject(data['progressiveStatus']);
      if (data.hasOwnProperty('clientId'))
        obj.clientId = ApiClient.convertToType(data['clientId'], 'Number');
      if (data.hasOwnProperty('candidateId'))
        obj.candidateId = ApiClient.convertToType(data['candidateId'], 'Number');
      if (data.hasOwnProperty('jobDescriptionId'))
        obj.jobDescriptionId = ApiClient.convertToType(data['jobDescriptionId'], 'Number');
      if (data.hasOwnProperty('jdAndCandidateStatusId'))
        obj.jdAndCandidateStatusId = ApiClient.convertToType(data['jdAndCandidateStatusId'], 'Number');
      if (data.hasOwnProperty('jdClientInterviewRounds'))
        obj.jdClientInterviewRounds = ApiClient.convertToType(data['jdClientInterviewRounds'], [JdClientInterviewRoundsCreateDto]);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
JdClientInterviewCreateDto.prototype.id = undefined;

/**
 * @member {String} uniqueGuid
 */
JdClientInterviewCreateDto.prototype.uniqueGuid = undefined;

/**
 * @member {module:model/InterviewStatus} status
 */
JdClientInterviewCreateDto.prototype.status = undefined;

/**
 * @member {module:model/ProgressiveStatus} progressiveStatus
 */
JdClientInterviewCreateDto.prototype.progressiveStatus = undefined;

/**
 * @member {Number} clientId
 */
JdClientInterviewCreateDto.prototype.clientId = undefined;

/**
 * @member {Number} candidateId
 */
JdClientInterviewCreateDto.prototype.candidateId = undefined;

/**
 * @member {Number} jobDescriptionId
 */
JdClientInterviewCreateDto.prototype.jobDescriptionId = undefined;

/**
 * @member {Number} jdAndCandidateStatusId
 */
JdClientInterviewCreateDto.prototype.jdAndCandidateStatusId = undefined;

/**
 * @member {Array.<module:model/JdClientInterviewRoundsCreateDto>} jdClientInterviewRounds
 */
JdClientInterviewCreateDto.prototype.jdClientInterviewRounds = undefined;

