/*
 * Extractor Engine API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.76(UAT)
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CandidateDto} from './CandidateDto';
import {ClientDto} from './ClientDto';
import {InterviewStatus} from './InterviewStatus';
import {JdAndCandidateStatusDto} from './JdAndCandidateStatusDto';
import {JdClientInterviewRoundsDto} from './JdClientInterviewRoundsDto';
import {JobDescriptionDto} from './JobDescriptionDto';
import {ProgressiveStatus} from './ProgressiveStatus';

/**
 * The JdClientInterviewCompactDto model module.
 * @module model/JdClientInterviewCompactDto
 * @version v3.76(UAT)
 */
export class JdClientInterviewCompactDto {
  /**
   * Constructs a new <code>JdClientInterviewCompactDto</code>.
   * @alias module:model/JdClientInterviewCompactDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>JdClientInterviewCompactDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/JdClientInterviewCompactDto} obj Optional instance to populate.
   * @return {module:model/JdClientInterviewCompactDto} The populated <code>JdClientInterviewCompactDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new JdClientInterviewCompactDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('uniqueGuid'))
        obj.uniqueGuid = ApiClient.convertToType(data['uniqueGuid'], 'String');
      if (data.hasOwnProperty('createdDate'))
        obj.createdDate = ApiClient.convertToType(data['createdDate'], 'Date');
      if (data.hasOwnProperty('status'))
        obj.status = InterviewStatus.constructFromObject(data['status']);
      if (data.hasOwnProperty('progressiveStatus'))
        obj.progressiveStatus = ProgressiveStatus.constructFromObject(data['progressiveStatus']);
      if (data.hasOwnProperty('clientId'))
        obj.clientId = ApiClient.convertToType(data['clientId'], 'Number');
      if (data.hasOwnProperty('client'))
        obj.client = ClientDto.constructFromObject(data['client']);
      if (data.hasOwnProperty('candidateId'))
        obj.candidateId = ApiClient.convertToType(data['candidateId'], 'Number');
      if (data.hasOwnProperty('candidate'))
        obj.candidate = CandidateDto.constructFromObject(data['candidate']);
      if (data.hasOwnProperty('jobDescriptionId'))
        obj.jobDescriptionId = ApiClient.convertToType(data['jobDescriptionId'], 'Number');
      if (data.hasOwnProperty('jobDescription'))
        obj.jobDescription = JobDescriptionDto.constructFromObject(data['jobDescription']);
      if (data.hasOwnProperty('jdAndCandidateStatusId'))
        obj.jdAndCandidateStatusId = ApiClient.convertToType(data['jdAndCandidateStatusId'], 'Number');
      if (data.hasOwnProperty('jdAndCandidateStatus'))
        obj.jdAndCandidateStatus = JdAndCandidateStatusDto.constructFromObject(data['jdAndCandidateStatus']);
      if (data.hasOwnProperty('jdClientInterviewRounds'))
        obj.jdClientInterviewRounds = ApiClient.convertToType(data['jdClientInterviewRounds'], [JdClientInterviewRoundsDto]);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
JdClientInterviewCompactDto.prototype.id = undefined;

/**
 * @member {String} uniqueGuid
 */
JdClientInterviewCompactDto.prototype.uniqueGuid = undefined;

/**
 * @member {Date} createdDate
 */
JdClientInterviewCompactDto.prototype.createdDate = undefined;

/**
 * @member {module:model/InterviewStatus} status
 */
JdClientInterviewCompactDto.prototype.status = undefined;

/**
 * @member {module:model/ProgressiveStatus} progressiveStatus
 */
JdClientInterviewCompactDto.prototype.progressiveStatus = undefined;

/**
 * @member {Number} clientId
 */
JdClientInterviewCompactDto.prototype.clientId = undefined;

/**
 * @member {module:model/ClientDto} client
 */
JdClientInterviewCompactDto.prototype.client = undefined;

/**
 * @member {Number} candidateId
 */
JdClientInterviewCompactDto.prototype.candidateId = undefined;

/**
 * @member {module:model/CandidateDto} candidate
 */
JdClientInterviewCompactDto.prototype.candidate = undefined;

/**
 * @member {Number} jobDescriptionId
 */
JdClientInterviewCompactDto.prototype.jobDescriptionId = undefined;

/**
 * @member {module:model/JobDescriptionDto} jobDescription
 */
JdClientInterviewCompactDto.prototype.jobDescription = undefined;

/**
 * @member {Number} jdAndCandidateStatusId
 */
JdClientInterviewCompactDto.prototype.jdAndCandidateStatusId = undefined;

/**
 * @member {module:model/JdAndCandidateStatusDto} jdAndCandidateStatus
 */
JdClientInterviewCompactDto.prototype.jdAndCandidateStatus = undefined;

/**
 * @member {Array.<module:model/JdClientInterviewRoundsDto>} jdClientInterviewRounds
 */
JdClientInterviewCompactDto.prototype.jdClientInterviewRounds = undefined;

