/*
 * Extractor Engine API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.76(UAT)
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {AttributeType} from './AttributeType';

/**
 * The MPathwayAttributeCreateDto model module.
 * @module model/MPathwayAttributeCreateDto
 * @version v3.76(UAT)
 */
export class MPathwayAttributeCreateDto {
  /**
   * Constructs a new <code>MPathwayAttributeCreateDto</code>.
   * @alias module:model/MPathwayAttributeCreateDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MPathwayAttributeCreateDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MPathwayAttributeCreateDto} obj Optional instance to populate.
   * @return {module:model/MPathwayAttributeCreateDto} The populated <code>MPathwayAttributeCreateDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MPathwayAttributeCreateDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('uniqueGuid'))
        obj.uniqueGuid = ApiClient.convertToType(data['uniqueGuid'], 'String');
      if (data.hasOwnProperty('attributeName'))
        obj.attributeName = ApiClient.convertToType(data['attributeName'], 'String');
      if (data.hasOwnProperty('attributeValue'))
        obj.attributeValue = ApiClient.convertToType(data['attributeValue'], 'String');
      if (data.hasOwnProperty('attributeType'))
        obj.attributeType = AttributeType.constructFromObject(data['attributeType']);
      if (data.hasOwnProperty('isCustomizable'))
        obj.isCustomizable = ApiClient.convertToType(data['isCustomizable'], 'Boolean');
      if (data.hasOwnProperty('apiUrl'))
        obj.apiUrl = ApiClient.convertToType(data['apiUrl'], 'String');
      if (data.hasOwnProperty('apiName'))
        obj.apiName = ApiClient.convertToType(data['apiName'], 'String');
      if (data.hasOwnProperty('mPathwayTypeId'))
        obj.mPathwayTypeId = ApiClient.convertToType(data['mPathwayTypeId'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
MPathwayAttributeCreateDto.prototype.id = undefined;

/**
 * @member {String} uniqueGuid
 */
MPathwayAttributeCreateDto.prototype.uniqueGuid = undefined;

/**
 * @member {String} attributeName
 */
MPathwayAttributeCreateDto.prototype.attributeName = undefined;

/**
 * @member {String} attributeValue
 */
MPathwayAttributeCreateDto.prototype.attributeValue = undefined;

/**
 * @member {module:model/AttributeType} attributeType
 */
MPathwayAttributeCreateDto.prototype.attributeType = undefined;

/**
 * @member {Boolean} isCustomizable
 */
MPathwayAttributeCreateDto.prototype.isCustomizable = undefined;

/**
 * @member {String} apiUrl
 */
MPathwayAttributeCreateDto.prototype.apiUrl = undefined;

/**
 * @member {String} apiName
 */
MPathwayAttributeCreateDto.prototype.apiName = undefined;

/**
 * @member {Number} mPathwayTypeId
 */
MPathwayAttributeCreateDto.prototype.mPathwayTypeId = undefined;

