/*
 * Extractor Engine API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.76(UAT)
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The MStepOutcomeCommunicationCompactDto model module.
 * @module model/MStepOutcomeCommunicationCompactDto
 * @version v3.76(UAT)
 */
export class MStepOutcomeCommunicationCompactDto {
  /**
   * Constructs a new <code>MStepOutcomeCommunicationCompactDto</code>.
   * @alias module:model/MStepOutcomeCommunicationCompactDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MStepOutcomeCommunicationCompactDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MStepOutcomeCommunicationCompactDto} obj Optional instance to populate.
   * @return {module:model/MStepOutcomeCommunicationCompactDto} The populated <code>MStepOutcomeCommunicationCompactDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MStepOutcomeCommunicationCompactDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('uniqueGuid'))
        obj.uniqueGuid = ApiClient.convertToType(data['uniqueGuid'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('mStepOutcomeId'))
        obj.mStepOutcomeId = ApiClient.convertToType(data['mStepOutcomeId'], 'Number');
      if (data.hasOwnProperty('mStepId'))
        obj.mStepId = ApiClient.convertToType(data['mStepId'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
MStepOutcomeCommunicationCompactDto.prototype.id = undefined;

/**
 * @member {String} uniqueGuid
 */
MStepOutcomeCommunicationCompactDto.prototype.uniqueGuid = undefined;

/**
 * @member {String} type
 */
MStepOutcomeCommunicationCompactDto.prototype.type = undefined;

/**
 * @member {String} message
 */
MStepOutcomeCommunicationCompactDto.prototype.message = undefined;

/**
 * @member {Number} mStepOutcomeId
 */
MStepOutcomeCommunicationCompactDto.prototype.mStepOutcomeId = undefined;

/**
 * @member {Number} mStepId
 */
MStepOutcomeCommunicationCompactDto.prototype.mStepId = undefined;

