/*
 * Extractor Engine API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.76(UAT)
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ParserType} from './ParserType';

/**
 * The ParserDto model module.
 * @module model/ParserDto
 * @version v3.76(UAT)
 */
export class ParserDto {
  /**
   * Constructs a new <code>ParserDto</code>.
   * @alias module:model/ParserDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ParserDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ParserDto} obj Optional instance to populate.
   * @return {module:model/ParserDto} The populated <code>ParserDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ParserDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('uniqueGuid'))
        obj.uniqueGuid = ApiClient.convertToType(data['uniqueGuid'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('userName'))
        obj.userName = ApiClient.convertToType(data['userName'], 'String');
      if (data.hasOwnProperty('userKey'))
        obj.userKey = ApiClient.convertToType(data['userKey'], 'String');
      if (data.hasOwnProperty('version'))
        obj.version = ApiClient.convertToType(data['version'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
      if (data.hasOwnProperty('serviceUrl'))
        obj.serviceUrl = ApiClient.convertToType(data['serviceUrl'], 'String');
      if (data.hasOwnProperty('dataModel'))
        obj.dataModel = ApiClient.convertToType(data['dataModel'], 'String');
      if (data.hasOwnProperty('parserType'))
        obj.parserType = ParserType.constructFromObject(data['parserType']);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
ParserDto.prototype.id = undefined;

/**
 * @member {String} uniqueGuid
 */
ParserDto.prototype.uniqueGuid = undefined;

/**
 * @member {String} name
 */
ParserDto.prototype.name = undefined;

/**
 * @member {String} userName
 */
ParserDto.prototype.userName = undefined;

/**
 * @member {String} userKey
 */
ParserDto.prototype.userKey = undefined;

/**
 * @member {String} version
 */
ParserDto.prototype.version = undefined;

/**
 * @member {String} password
 */
ParserDto.prototype.password = undefined;

/**
 * @member {String} serviceUrl
 */
ParserDto.prototype.serviceUrl = undefined;

/**
 * @member {String} dataModel
 */
ParserDto.prototype.dataModel = undefined;

/**
 * @member {module:model/ParserType} parserType
 */
ParserDto.prototype.parserType = undefined;

