/*
 * Extractor Engine API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.76(UAT)
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ProjectSkillEditDto model module.
 * @module model/ProjectSkillEditDto
 * @version v3.76(UAT)
 */
export class ProjectSkillEditDto {
  /**
   * Constructs a new <code>ProjectSkillEditDto</code>.
   * @alias module:model/ProjectSkillEditDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ProjectSkillEditDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProjectSkillEditDto} obj Optional instance to populate.
   * @return {module:model/ProjectSkillEditDto} The populated <code>ProjectSkillEditDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProjectSkillEditDto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('skillPlatformName'))
        obj.skillPlatformName = ApiClient.convertToType(data['skillPlatformName'], 'String');
      if (data.hasOwnProperty('candidateSkillPlatformId'))
        obj.candidateSkillPlatformId = ApiClient.convertToType(data['candidateSkillPlatformId'], 'Number');
      if (data.hasOwnProperty('projectId'))
        obj.projectId = ApiClient.convertToType(data['projectId'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
ProjectSkillEditDto.prototype.id = undefined;

/**
 * @member {String} skillPlatformName
 */
ProjectSkillEditDto.prototype.skillPlatformName = undefined;

/**
 * @member {Number} candidateSkillPlatformId
 */
ProjectSkillEditDto.prototype.candidateSkillPlatformId = undefined;

/**
 * @member {Number} projectId
 */
ProjectSkillEditDto.prototype.projectId = undefined;

