/*
 * Extractor Engine API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3.76(UAT)
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ProjSkill model module.
 * @module model/ProjSkill
 * @version v3.76(UAT)
 */
export class ProjSkill {
  /**
   * Constructs a new <code>ProjSkill</code>.
   * @alias module:model/ProjSkill
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ProjSkill</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProjSkill} obj Optional instance to populate.
   * @return {module:model/ProjSkill} The populated <code>ProjSkill</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProjSkill();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
ProjSkill.prototype.name = undefined;

